General:
  Stats_Tracking_Enabled: true
  Update_Check_Enabled: true
Duel:
  Prevent_PVP: false
  Override_PVP: true
  Save_Inventory: true
  Invitation_Timeout: 30
  Duel_Length: 120
Arena:
  Knockback_Enabled: true
  Radius: 20.0
Challenge:
  Duel_Items:
    - Diamond_Sword
    - Diamond_Axe
    - Gold_Sword
    - Gold_Axe
    - Iron_Sword
    - Iron_Axe
    - Stone_Sword
    - Stone_Axe
    - Wood_Sword
    - Wood_Axe