General:
  Stats_Tracking_Enabled: true
  Update_Check_Enabled: true
Duel:
  Prevent_PVP: false
  Override_PVP: true
  Save_Inventory: true
  Invitation_Timeout: 30
  Duel_Length: 120
Arena:
  Knockback_Enabled: true
  Radius: 20.0